Public Class ClsResult
    Public AUCTION_NUM, LOT_NUM, YEAR, MODEL_NAME, GRADE, MODEL, CC, REGISTRATION_TIME, KM, COLOR, TRANSMISSION, CONDITIONER, AUDION_GRADE, EXTERIOR_GRADE, INTERIOR_GRADE, START_PRICE, LOT_STATUS, AUCTION_DATE, AUCTION_TIME, FINAL_PRICE, VIN, EQUIPMENT, PICTURE1_LINK, PICTURE2_LINK, PICTURE3_LINK, PICTURE4_LINK, STEERING As String
    Public ThreadInsert As Integer
End Class
